<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'FormBuilder\Module'                        => __DIR__ . '/Module.php',
    'FormBuilder\Controller\FormBuilderController' => __DIR__ . '/src/FormBuilder/Controller/FormBuilderController.php',
    'FormBuilderTest\Framework\TestCase'        => __DIR__ . '/tests/FormBuilder/Framework/TestCase.php',
    'FormBuilderTest\SampleTest'                => __DIR__ . '/tests/FormBuilder/SampleTest.php',
);
