<?php foreach($formbuilders as $formbuilder):?>
<div class="row clearfix">
	<!-- Building Form. -->
	<div class="span12">
		<div class="clearfix">
			<h2><?php echo $formbuilder->getName() ?></h2>
			<hr>
			<!-- Button -->
            <div class="control-group">
              <div class="controls">
                <button id="save" name="save" class="btn btn-primary">Save</button>
              </div>
            </div>
			<div id="build">
    			<div id="stickynote-<?php echo $formbuilder->getId() ?>">
    			    <form id="target" class="form-horizontal"></form>
    			</div>
			</div>
		</div>
	</div>
	<!-- / Building Form. -->

	<!-- Components -->
	<div class="span12">
		<h2>Drag & Drop components</h2>
		<hr>
		<div class="tabbable">
			<ul class="nav nav-tabs" id="formtabs">
				<!-- Tab nav -->
			</ul>
			<form class="form-horizontal" id="components">
				<fieldset>
					<div class="tab-content">
						<!-- Tabs of snippets go here -->
					</div>
				</fieldset>
			</form>
		</div>
	</div>
	<!-- / Components -->
</div>
<?php endforeach; ?>