<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('FormBuilder ' . $this->translate('Sticky Notes'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/assets/css/lib/bootstrap.min.css')
                ->prependStylesheet($this->basePath() . '/assets/css/lib/bootstrap-responsive.min.css')
                ->prependStylesheet($this->basePath() . '/assets/css/custom.css')
//                 <link href="assets/css/lib/bootstrap.min.css" rel="stylesheet">
//                 <link href="assets/css/lib/bootstrap-responsive.min.css" rel="stylesheet">
//                 <link href="assets/css/custom.css" rel="stylesheet">
                
                // style for FormBuilder
//                 ->prependStylesheet($this->basepath() . '/formbuilder/css/custom.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/assets/js/main-built.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                // <script data-main="assets/js/main-built.js" src="assets/js/lib/require.js" ></script>
                ->appendFile($this->basepath() . '/assets/js/main-built.js')
//                 ->appendFile($this->basepath() . '/assets/js/lib/require.js')
        ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Sticky Notes') ?></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="navbar navbar-fixed-top">
          <div class="navbar-inner">
            <div class="container">
              <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Sticky Notes') ?></a>
              <div class="nav-collapse collapse">
                <ul class="nav">
                    <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                </ul>
            </div><!--/.nav-collapse -->
            </div>
          </div>
        </div>
        <div class="container">
<?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - 2012 by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
                <p>Handcrafted with ♥ in Los Angeles by Big Employee LLC.</p>
            </footer>
        </div> <!-- /container -->
<?php echo $this->inlineScript() ?>
    </body>
</html>
